// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LeVanTru0714.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230623014814_Create_Table_LVTSV")]
    partial class Create_Table_LVTSV
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.8");

            modelBuilder.Entity("LeVanTru0714.Models.LVTSinhVien", b =>
                {
                    b.Property<int>("LVTMaSinhVien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("LVTTenSinhVien")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("LVTTuoi")
                        .HasColumnType("REAL");

                    b.HasKey("LVTMaSinhVien");

                    b.ToTable("LVTSinhVien");
                });
#pragma warning restore 612, 618
        }
    }
}
